# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 757)
        MainWindow.setMinimumSize(QtCore.QSize(1039, 757))
        MainWindow.setMaximumSize(QtCore.QSize(1039, 757))
        MainWindow.setStyleSheet("QWidget#centralwidget{border-image: url(:/ha/two.jpg);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 660, 101, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(67, 67, 67);")
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(50, 560, 100, 100))
        self.graphicsView_2.setStyleSheet("border-image: url(:/ha/QQ图片20190529192028.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(200, 560, 101, 121))
        self.graphicsView_3.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 80, 301, 121))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: 22pt \"黑体\";\n"
"background-color: rgba(255, 255, 255, 150);\n"
"color: rgb(200, 66, 100);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 230, 501, 121))
        self.lineEdit_2.setStyleSheet("font: 22pt \"黑体\";\n"
"background-color: rgba(255, 255, 255, 150);\n"
"color: rgb(200, 66, 100);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 380, 501, 121))
        self.lineEdit_3.setStyleSheet("font: 22pt \"黑体\";\n"
"color: rgb(200, 66, 100);\n"
"background-color: rgba(255, 255, 255, 150);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(250, 560, 101, 121))
        self.graphicsView_4.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(300, 560, 101, 121))
        self.graphicsView_5.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_6.setGeometry(QtCore.QRect(350, 560, 101, 121))
        self.graphicsView_6.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(400, 560, 101, 121))
        self.graphicsView_7.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(450, 560, 101, 121))
        self.graphicsView_8.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(500, 560, 101, 121))
        self.graphicsView_9.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_10.setGeometry(QtCore.QRect(550, 560, 101, 121))
        self.graphicsView_10.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.graphicsView_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_11.setGeometry(QtCore.QRect(600, 560, 101, 121))
        self.graphicsView_11.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_12.setGeometry(QtCore.QRect(650, 560, 101, 121))
        self.graphicsView_12.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.graphicsView_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_13.setGeometry(QtCore.QRect(700, 560, 101, 121))
        self.graphicsView_13.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.graphicsView_14 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_14.setGeometry(QtCore.QRect(750, 560, 101, 121))
        self.graphicsView_14.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.graphicsView_15 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_15.setGeometry(QtCore.QRect(800, 560, 101, 121))
        self.graphicsView_15.setStyleSheet("border-image: url(:/en/A.jpg);")
        self.graphicsView_15.setObjectName("graphicsView_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(MainWindow.backmenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>玩家1</p></body></html>"))
        self.label.setText(_translate("MainWindow", "易烊千玺"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "前墩"))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainWindow", "中墩"))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit_3.setText(_translate("MainWindow", "后墩"))
        self.pushButton_4.setText(_translate("MainWindow", "<"))
import xixi_rc
