# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1039, 757)
        Dialog.setMinimumSize(QtCore.QSize(1039, 757))
        Dialog.setMaximumSize(QtCore.QSize(1039, 757))
        Dialog.setStyleSheet("QDialog#Dialog {\n"
"    \n"
"    \n"
"    border-image: url(:/新前缀/images/QQ图片20191010185657.jpg);\n"
"}")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 50, 1031, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(380, 30, 271, 61))
        self.graphicsView.setStyleSheet("border-image: url(:/新前缀/images/QQ截图20191011224126.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(40, 140, 961, 71))
        self.frame_2.setStyleSheet("QFrame#frame_2 {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 3px solid #FFFFFF 3px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(40, 220, 961, 71))
        self.frame_3.setStyleSheet("QFrame#frame_3 {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 3px solid #FFFFFF 3px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 961, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.id1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.id1.setFont(font)
        self.id1.setStyleSheet("color: rgb(35, 35, 35);")
        self.id1.setText("")
        self.id1.setAlignment(QtCore.Qt.AlignCenter)
        self.id1.setObjectName("id1")
        self.horizontalLayout_2.addWidget(self.id1)
        self.card1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.card1.setFont(font)
        self.card1.setText("")
        self.card1.setAlignment(QtCore.Qt.AlignCenter)
        self.card1.setObjectName("card1")
        self.horizontalLayout_2.addWidget(self.card1)
        self.point1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.point1.setFont(font)
        self.point1.setStyleSheet("color: rgb(35, 35, 35);")
        self.point1.setText("")
        self.point1.setAlignment(QtCore.Qt.AlignCenter)
        self.point1.setObjectName("point1")
        self.horizontalLayout_2.addWidget(self.point1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(40, 300, 961, 71))
        self.frame_4.setStyleSheet("QFrame#frame_4 {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 3px solid #FFFFFF 3px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, -1, 961, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.id2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.id2.setFont(font)
        self.id2.setStyleSheet("color: rgb(35, 35, 35);")
        self.id2.setText("")
        self.id2.setAlignment(QtCore.Qt.AlignCenter)
        self.id2.setObjectName("id2")
        self.horizontalLayout_3.addWidget(self.id2)
        self.card2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.card2.setFont(font)
        self.card2.setText("")
        self.card2.setAlignment(QtCore.Qt.AlignCenter)
        self.card2.setObjectName("card2")
        self.horizontalLayout_3.addWidget(self.card2)
        self.point2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.point2.setFont(font)
        self.point2.setStyleSheet("color: rgb(35, 35, 35);")
        self.point2.setText("")
        self.point2.setAlignment(QtCore.Qt.AlignCenter)
        self.point2.setObjectName("point2")
        self.horizontalLayout_3.addWidget(self.point2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(40, 380, 961, 71))
        self.frame_5.setStyleSheet("QFrame#frame_5 {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 3px solid #FFFFFF 3px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 961, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.id3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.id3.setFont(font)
        self.id3.setStyleSheet("color: rgb(35, 35, 35);")
        self.id3.setText("")
        self.id3.setAlignment(QtCore.Qt.AlignCenter)
        self.id3.setObjectName("id3")
        self.horizontalLayout_4.addWidget(self.id3)
        self.card3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.card3.setFont(font)
        self.card3.setText("")
        self.card3.setAlignment(QtCore.Qt.AlignCenter)
        self.card3.setObjectName("card3")
        self.horizontalLayout_4.addWidget(self.card3)
        self.point3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.point3.setFont(font)
        self.point3.setStyleSheet("color: rgb(35, 35, 35);")
        self.point3.setText("")
        self.point3.setAlignment(QtCore.Qt.AlignCenter)
        self.point3.setObjectName("point3")
        self.horizontalLayout_4.addWidget(self.point3)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(40, 460, 961, 71))
        self.frame_6.setStyleSheet("QFrame#frame_6 {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 3px solid #FFFFFF 3px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 961, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.id4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.id4.setFont(font)
        self.id4.setStyleSheet("color: rgb(35, 35, 35);")
        self.id4.setText("")
        self.id4.setAlignment(QtCore.Qt.AlignCenter)
        self.id4.setObjectName("id4")
        self.horizontalLayout_5.addWidget(self.id4)
        self.card4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.card4.setFont(font)
        self.card4.setText("")
        self.card4.setAlignment(QtCore.Qt.AlignCenter)
        self.card4.setObjectName("card4")
        self.horizontalLayout_5.addWidget(self.card4)
        self.point4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.point4.setFont(font)
        self.point4.setStyleSheet("color: rgb(35, 35, 35);")
        self.point4.setText("")
        self.point4.setAlignment(QtCore.Qt.AlignCenter)
        self.point4.setObjectName("point4")
        self.horizontalLayout_5.addWidget(self.point4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(690, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(800, 105, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(930, 105, 41, 31))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(310, 580, 411, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)

        self.retranslateUi(Dialog)
        self.pushButton_4.clicked.connect(Dialog.backmenu)
        self.pushButton_2.clicked.connect(Dialog.nextpage1)
        self.pushButton_3.clicked.connect(Dialog.frontpage1)
        self.pushButton.clicked.connect(Dialog.search)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "用户名"))
        self.label_2.setText(_translate("Dialog", "出牌情况"))
        self.label_3.setText(_translate("Dialog", "积分"))
        self.label_5.setText(_translate("Dialog", "战局查询"))
        self.lineEdit.setWhatsThis(_translate("Dialog", "<html><head/><body><p>请输入id</p></body></html>"))
        self.lineEdit.setText(_translate("Dialog", "请输入id"))
        self.pushButton.setText(_translate("Dialog", "✔"))
        self.pushButton_4.setText(_translate("Dialog", "<"))
        self.pushButton_3.setText(_translate("Dialog", "上一页<<<"))
        self.label_4.setText(_translate("Dialog", "1"))
        self.pushButton_2.setText(_translate("Dialog", ">>>下一页"))
import loginimg_rc
